Repository OpenFloodAI/openfloodai.github.io, pull requests merged in 2019-10, with the labels that each got.

#7 Added Twitter feed to index page
  .vs/openfloodai.github.io/config/applicationhost.config
  .vs/slnx.sqlite
  index.html
Labels: Hacktoberfest, enhancement

#11 Create sections and add social links
  index.html
Labels: Hacktoberfest, enhancement

#39 Edited readme.md to help contributors
  README.md
Labels: Hacktoberfest

#74 Add new card about Climate change datasets
  index.html
Labels: enhancement
